### PR TITLE
add unsafe limiter

### PR DESCRIPTION
**Pull request by mmaxiaolei**
usage scenario: single thread(goroutine)

### CODE REVIEW

**Comment by mmaxiaolei** [comment]
TRY CLA

**Comment by rabbbit** [comment]
Hi,

Thanks for the contribution!

What's the actual use-case for this? Given the low over-head of the current implementations, and the limitation of a single go-routine, would the "default" limiter not just work?

We thought about possibly extending the API to return different types of rate-limiters depending on the use-case, but I wasn't planning to do it via options. Would need to punt on this a bit more.

**Comment by mmaxiaolei** [comment]
@rabbbit thank you for your reply!

the "default" limiter can work. but we use in cloud native,we want high-performance and low over-head without mutex and cas

and i agree your point about different limiter without options. However, the current design can not be well extended, especially CAS may cause "starvation" in high concurrency scenarios

**Comment by rabbbit** [comment]
> . but we use in cloud native

What do you mean cloud native? Is there a particular application you're needing this in?

> However, the current design can not be well extended, especially CAS may cause "starvation" in high concurrency scenarios

Well, yeah ... but this diff is about having rate limiter in concurrency=1 scenarios, so starvation shouldn't be a problem?
I'm a bit confused now.

**Comment by rabbbit** [comment]
Closing for now - please respond if you still think it's valuable :)

**Pull request closed without merging**
