### PR TITLE
Add Per option

### PR DESCRIPTION
**Pull request by kriskowal**
Commits are individually reviewable.
The first changes address nits I missed in review.

The final change addresses #17 by adding an option called Per that reads
ratelimit.New(1, Per(time.Second)) for a 1Hz rate limiter.

### CODE REVIEW

**Comment by l3uddz** [comment]
thanks!

hoping this gets merged soon.

not sure how else to use this package if trying to enforce a 150 requests per hour scenario.

**Comment by jvonfricken** [comment]
Looks like exactly what I need. 

Any idea if this PR is planning to get merged?

**Comment by addeshmu** [comment]
Thanks for great lib, and this PR, can this PR be merged for added functionality? will help us cater to more versatile rate limiting scenarios.

**Comment by Jleagle** [comment]
https://github.com/uber-go/ratelimit/pull/17/files was closed in favour of this, which never got merged.

**Comment by nightwolfz** [comment]
It's been a year...

**Comment by rabbbit** [comment]
Replaced by #54

**Pull request closed without merging**
